import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import SanityContent from "../components/SanityContent";
import Section2 from "../components/Section2";

import blob from "../static/designer_1.png";
import rectangle from "../static/Rectangle.svg";

export default function Home() {
  return (
    <>
      <div className="flex flex-col px-2">
        <Head>
          <title>This is Landie 1.0</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Image
          src={blob}
          alt="Picture of the author"
          width={540}
          height={100}
          className="hidden mt-6 right-0 -z-10 md:absolute md:block top-0"
        />
        <Header />
        <section id="hero">
          <div className="container flex flex-col-reverse md:flex-row items-center px-1 mx-auto mt-3 space-y-0 md:space-y-1 mb-8">
            <div className="flex flex-col mb-32 space-y-12 md:w-1/2 md:pl-8 md:pt-section-feat">
              <h1 className=" mb-2">
                Introduce Your Product
                <br /> Quickly &&nbsp;Effectively
              </h1>
              <p className="max-w-xl text-l leading-l font-normal  text-blue-500 mb-1">
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
                commodo ligula eget dolor. Aenean massa. Cum sociis natoque
                penatibus et magnis dis parturient montes, nascetur ridiculus
              </p>
              <p className="max-w-xl text-l leading-l font-normal  text-blue-500 mb-6">
                mus. Donec quam felis, ultricies nec, pellentesque eu, pretium
                quis, sem. Nulla consequat massa quis enim.
              </p>
              <div className="flex items-center flex-col md:flex-row md:items-start">
                <Link
                  href="/"
                  className="py-1 font-medium text-center text-white bg-blue-800 text-xs leading-xs w-button h-button rounded-sm hover:bg-blue-600 md:mr-5 mb-1 outline outline-1 outline-gray-700"
                >
                  Purchase UI Kit
                </Link>
                <Link
                  href="/"
                  className="py-1 font-medium text-center text-gray-700 bg-transparent text-xs leading-xs w-button h-button rounded-sm hover:bg-blue-600 outline outline-1 outline-gray-700 hover:text-white"
                >
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section id="features">
          <div className="container flex flex-col-reverse mx-auto mt-10 md:space-y-0 md:flex-row ">
            <div className="flex flex-col  lg:pt-section-feat lg:pl-section-feat2 md:w-73 lg:w-51">
              <h2>Light, Fast&nbsp;&&nbsp;Powerful</h2>
              <p className="text-m leading-m font-normal  text-gray-600 mb-1">
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
                commodo ligula eget dolor. Aenean massa. Cum sociis natoque
                penatibus et magnis dis parturient montes, nascetur ridiculus
              </p>
              <p className="text-m leading-m font-normal  text-gray-600 mb-6">
                mus. Donec quam felis, ultricies nec, pellentesque eu, pretium
                quis, sem. Nulla consequat massa quis enim.
              </p>
              <div className="flex">
                <div className="flex-column md:w-1/2 mr-5">
                  <Image
                    width={36}
                    height={36}
                    src={blob}
                    alt="icon"
                    className="mb-3"
                  ></Image>
                  <h3>Title Goes Here</h3>
                  <p className="text-xs leading-xs text-gray-600">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                    Aenean commodo ligula eget dolor.
                  </p>
                </div>
                <div className="flex-column  md:w-1/2">
                  <Image
                    width={36}
                    height={36}
                    src={blob}
                    alt="icon"
                    className="mb-3"
                  ></Image>
                  <h3>Title Goes Here</h3>
                  <p className="text-xs leading-xs text-gray-600">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                    Aenean commodo ligula eget dolor.
                  </p>
                </div>
              </div>
            </div>
            <Image
              width={480}
              height={315}
              src={blob}
              alt="icon"
              className="hidden md:flex"
            ></Image>
          </div>
        </section>
        <section id="features-2">
          <div className="container flex flex-col mx-auto mt-10 md:space-y-0 md:flex-row mb-32">
            <Image
              width={480}
              height={315}
              src={blob}
              alt="icon"
              className="hidden md:flex"
            />
            <div className="flex flex-col  lg:pt-section-feat lg:pl-section-feat2  md:w-73 lg:w-42">
              <h2>Light, Fast&nbsp;&&nbsp;Powerful</h2>
              <p className="text-m leading-m font-normal  text-gray-600 mb-1">
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
                commodo ligula eget dolor. Aenean massa. Cum sociis natoque
                penatibus et magnis dis parturient montes, nascetur ridiculus
              </p>
              <p className="text-m leading-m font-normal  text-gray-600 mb-6">
                mus. Donec quam felis, ultricies nec, pellentesque eu, pretium
                quis, sem. Nulla consequat massa quis enim.
              </p>
            </div>
          </div>
        </section>
        <section id="features-3">
          <div
            className=" flex flex-col max-w-xl  text-center items-center"
            style={{ margin: "auto" }}
          >
            <h2 className="mt-60">A Price To Suit Everyone</h2>
            <p className="text-m leading-m font-normal  text-gray-600 mb-5">
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
              commodo ligula eget dolor. Aenean massa. Cum sociis natoque
              penatibus et magnis dis parturient montes, nascetur ridiculus
            </p>
            <h4>$40</h4>
            <p className="text-m leading-m font-normal  text-blue-600 mb-7">
              UI Design Kit
            </p>
            <p className="text-s leading-s font-normal  text-gray-600 mb-2.5">
              See, One price. Simple.
            </p>
            <Link
              href="/"
              className="py-1 font-medium text-center text-white bg-blue-800 text-xs leading-xs w-button h-button rounded-sm hover:bg-blue-600  mb-1 outline outline-1 outline-gray-700"
            >
              Purchase Now
            </Link>
          </div>
        </section>
      </div>
      <div
        style={{
          zIndex: "-1",
          backgroundImage: "url('../static/Rectangle.svg')",
          backgroundRepeat: "no-repeat",
          height: "75vh",
          marginTop: "-64vh",
        }}
      />
      <footer className="bg-blue-100">
        <div className="container justify-between px-6 py-10 mx-auto space-y-8 md:flex-row md:space-y-0">
          <div className="items-middle justify-between md:flex md:space-x-8">
            <p className="text-s leading-s font-medium  text-gray-400">
              ©2020 Yourcompany
            </p>
            <div className="text-xl leading-xl text-blue-primary text-landie font-black">
              <span>Landie</span>
            </div>
            <Link
              href="/"
              className="py-1 font-medium text-center text-white bg-blue-800 text-xs leading-xs w-button h-button rounded-sm hover:bg-blue-600  outline outline-1 outline-gray-700"
            >
              Purchase Now
            </Link>
          </div>
        </div>
      </footer>
    </>
  );
}
