import Head from "next/head";
import Image from "next/image";

import Header from "../components/Header";

import blob from "../static/Path.png";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>This is Landie 1.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src={blob}
        alt="Picture of the author"
        width={500}
        height={500}
        className="absolute right-0 -z-10"
      />
      <Header />
      <div className="flex">
        <div className="px-10 space-y-5 max-w-xl">
          <h1 className="text-5xl max-w-xl">
            Introduce Your Product
            <br /> Quickly & Effectively
          </h1>
          <h2>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            commodo ligula eget dolor. Aenean massa. Cum sociis natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
            Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.
            Nulla consequat massa quis enim.
          </h2>
        </div>
      </div>
      {/* Posts */}
    </div>
  );
}
