import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import Hero from "../components/Hero";
import SanityContent from "../components/SanityContent";

import blob from "../static/designer_1.png";
import rectangle from "../static/Rectangle.svg";
import Footer from "../components/Footer";
import ThirdSection from "../components/ThirdSection";
import SecondSection from "../components/SecondSection";
import FirstSection from "../components/FirstSection";

export default function Home() {
  return (
    <>
      <div className="flex flex-col px-5 md:px-20">
        <Head>
          <title>This is Landie 1.0</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Image
          src={blob}
          alt="Picture of the author"
          width={540}
          height={100}
          className="hidden mt-6 right-0 -z-10 md:absolute md:block top-0"
        />
        <Header />
        <Hero />
        <FirstSection />
        <SecondSection />
        <ThirdSection />
      </div>
      <div
        style={{
          zIndex: "-1",
          backgroundImage: "url('../static/Rectangle.svg')",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          height: "75vh",
          marginTop: "-64vh",
        }}
      />
      <Footer />
    </>
  );
}
